# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = uwsm app -- bash -c 'SSH_ASKPASS=~/.local/bin/ssh-askpass-keyring SSH_ASKPASS_REQUIRE=prefer ssh-add ~/.ssh/richard_ed25519'
