# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket
env = XCURSOR_THEME,Caiptain-Gruvbox
env = XCURSOR_SIZE,34
env = HYPRCURSOR_THEME,Caiptain-Gruvbox
env = HYPRCURSOR_SIZE,34
