windowrule = no_screen_share on, match:class ^(Bluetooth Devices)$
windowrule = tag +floating-window, match:class ^(Bluetooth Devices)$

# --- Steam Fixes ---
windowrule = float 0, match:class ^(steam)$, match:title ^(Steam)$
windowrule = tile 1, match:class ^(steam)$, match:title ^(Steam)$
windowrule = float 1, match:class ^(steam)$, match:title ^(Friends List|Settings|Properties)$

# --- Game Fixes (Excluding Steam) ---
windowrule = opacity 1.0 override 1.0 override, match:xwayland 1
windowrule = fullscreen 1, match:xwayland 1, match:class negative:^(steam)$

