return {
	-- "milanglacier/minuet-ai.nvim",
	-- dependencies = {
	-- 	{ "nvim-lua/plenary.nvim" },
	-- 	{ "Saghen/blink.cmp" },
	-- },
	-- opts = {
	-- 	request_timeout = 2,
	-- 	context_window = 384,
	-- 	provider = "claude",
	-- 	-- notify = "debug",
	-- 	provider_options = {
	-- 		claude = {
	-- 			-- model = "claude-3-5-sonnet-20240620",
	-- 			model = "claude-3-5-haiku-20241022", -- Fastest but less accurate
	-- 			optional = {
	-- 				temperature = 0.1,
	-- 				max_tokens = 70,
	-- 			},
	-- 		},
	-- 	},
	-- },
}
